const { v4 } =  require('uuid');

exports.seed = function(knex) {
  // Deletes ALL existing entries
  return knex('sites').del()
    .then(function () {
      // Inserts seed entries
      return knex('sites').insert([
        { id: v4(), type: 'School', site_name: 'Arcadia High', site_code: 'ARC', code_number: '2000', district:  'Tygerberg'},
        { id: v4(), type: 'School', site_name: 'Athlone High', site_code: 'ATH', code_number: '2000', district:  'Klipfontein'},
        { id: v4(), type: 'School', site_name: 'Belgravia High', site_code: 'BEL', code_number: '2000', district:  'Kilpfontein'},
        { id: v4(), type: 'School', site_name: 'Bonteheuwel High', site_code: 'BON', code_number: '2000', district:  'Tygerberg'},
        { id: v4(), type: 'School', site_name: 'Crystal High', site_code: 'CRY', code_number: '2000', district:  'Klipfontein'},
        { id: v4(), type: 'School', site_name: 'Fezeka High', site_code: 'FEZ', code_number: '2000', district:  'Klipfontein'},
        { id: v4(), type: 'School', site_name: 'Heideveld High', site_code: 'HEI', code_number: '2000', district:  'Klipfontein'},
        { id: v4(), type: 'School', site_name: 'Intsebenziswano High', site_code: 'INT', code_number: '2000', district:  'Mitchells Plain'},
        { id: v4(), type: 'School', site_name: 'Manenberg High', site_code: 'MAN', code_number: '2000', district:  'Klipfontein'},
        { id: v4(), type: 'School', site_name: 'Modderdam High', site_code: 'MOD', code_number: '2000', district:  'Klipfontein'},
        { id: v4(), type: 'School', site_name: 'New Eisleben', site_code: 'NEW', code_number: '2000', district:  'Mitchells Plain'},
        { id: v4(), type: 'School', site_name: 'Oaklands High', site_code: 'OAK', code_number: '2000', district:  'Klipfontein'},
        { id: v4(), type: 'School', site_name: 'Phandulwazi High', site_code: 'PHA', code_number: '2000', district:  'Mitchells Plain'},
        { id: v4(), type: 'School', site_name: 'Phoenix High', site_code: 'PHO', code_number: '2000', district:  'Klipfontein'},
        { id: v4(), type: 'School', site_name: 'Rylands High', site_code: 'RYL', code_number: '2000', district:  'Klipfontein'},
        { id: v4(), type: 'School', site_name: 'Sophumelela High', site_code: 'SOP', code_number: '2000', district:  'Mitchells Plain'},
        { id: v4(), type: 'School', site_name: 'Spes Bona High', site_code: 'SPES', code_number: '2000', district:  'Klipfontein'},
        { id: v4(), type: 'School', site_name: 'Vuyiseka High', site_code: 'Vuy', code_number: '2000', district:  'Mitchells Plain'},
        { id: v4(), type: 'School', site_name: 'Windsor High', site_code: 'WIN', code_number: '2000', district:  'Klipfontein'},
        { id: v4(), type: 'School', site_name: 'Zeekoevlei', site_code: 'ZEE', code_number: '2000', district:  'Southern'},
        { id: v4(), type: 'School', site_name: 'Christel House High', site_code: 'CHR', code_number: '2000', district:  'Klipfontein'},
        { id: v4(), type: 'School', site_name: 'Fairmount High', site_code: 'FAI', code_number: '2000', district:  'Southern'},
        { id: v4(), type: 'School', site_name: 'Garlandale High', site_code: 'GAR', code_number: '2000', district:  'Klipfontein'},
        { id: v4(), type: 'School', site_name: 'Peak View High', site_code: 'PEA', code_number: '2000', district:  'Klipfontein'},
        { id: v4(), type: 'School', site_name: 'Abotts College', site_code: 'CABO', code_number: '2000', district:  'Southern'},
        { id: v4(), type: 'School', site_name: 'Athlone College', site_code: 'CATH', code_number: '2000', district:  'Klipfontein'},
        { id: v4(), type: 'School', site_name: 'C.P.U.T. Nursing College', site_code: 'UCNUR', code_number: '2000', district:  'Tygerberg'},
        { id: v4(), type: 'School', site_name: 'College of Cape Town (Crawford)', site_code: 'CTCRA', code_number: '2000', district:  'Klipfontein'},
        { id: v4(), type: 'School', site_name: 'College of Cape Town Gugulethu', site_code: 'CTGUG', code_number: '2000', district:  'Klipfontein'},
        { id: v4(), type: 'School', site_name: 'College of Cape Town Pinelands', site_code: 'CTPIN', code_number: '2000', district:  'Western'},
        { id: v4(), type: 'School', site_name: 'Goodwood College', site_code: 'CGOOD', code_number: '2000', district:  'Western'},
        { id: v4(), type: 'School', site_name: 'C.P.U.T Mowbray', site_code: 'UCMOW', code_number: '2000', district:  'Western'},
        { id: v4(), type: 'School', site_name: 'C.P.U.T Tygerberg', site_code: 'UCTYG', code_number: '2000', district:  'Tygerberg'},
        { id: v4(), type: 'School', site_name: 'C.P.U.T. Bellville', site_code: 'UCBEL', code_number: '2000', district:  'Tygerberg'},
        { id: v4(), type: 'School', site_name: 'C.P.U.T. Cape Penisula University of Technology', site_code: 'UCPUT', code_number: '2000', district:  'Tygerberg'},
        { id: v4(), type: 'School', site_name: 'C.P.U.T. Cape Town', site_code: 'UCCT', code_number: '2000', district:  'Cape Central'},
        { id: v4(), type: 'School', site_name: 'COCT- City Campus', site_code: 'CTCT', code_number: '2000', district:  'Western'},
        { id: v4(), type: 'School', site_name: 'CPUT Granger Bay Campus', site_code: 'UCGRA', code_number: '2000', district:  'Western'},
        { id: v4(), type: 'School', site_name: 'Northlink College-Parow Campus', site_code: 'CNPAR', code_number: '2000', district:  'Tygerberg'},
        { id: v4(), type: 'School', site_name: 'Nursing College Athlone', site_code: 'CATHN', code_number: '2000', district:  'Klipfontein'},
        { id: v4(), type: 'School', site_name: 'Rosebank College', site_code: 'CROS', code_number: '2000', district:  'Western'},
        { id: v4(), type: 'School', site_name: 'Thornton Campus', site_code: 'CTHO', code_number: '2000', district:  'Tygerberg'},
        { id: v4(), type: 'School', site_name: 'Tygerberg Medical Campus', site_code: 'TYGM', code_number: '2000', district:  'Tygerberg'},
        { id: v4(), type: 'School', site_name: 'UCT (University of Cape Town)', site_code: 'UUCT', code_number: '2000', district:  'Western'},
        { id: v4(), type: 'School', site_name: 'Stellenbosch University', site_code: 'USTE', code_number: '2000', district:  'Winelands'},
        { id: v4(), type: 'School', site_name: 'Vega College', site_code: 'CVEG', code_number: '2000', district:  'Western'},
        { id: v4(), type: 'School', site_name: 'Wynberg College', site_code: 'CWYN', code_number: '2000', district:  'Southern'},
        { id: v4(), type: 'School', site_name: 'C.O.C Athlone', site_code: 'CTATH', code_number: '2000', district:  'Klipfontein'},
        { id: v4(), type: 'School', site_name: 'C.O.C Crawford', site_code: 'CTCRA', code_number: '2000', district:  'Klipfontein'},
        { id: v4(), type: 'School', site_name: 'C.O.C Garden', site_code: 'CTGAR', code_number: '2000', district:  'Cape Central'},
        { id: v4(), type: 'School', site_name: 'C.O.C Wynberg', site_code: 'CTWYN', code_number: '2000', district:  'Southern'},
        { id: v4(), type: 'Community', site_name: 'Access Park', site_code: '', code_number: '', district:  'Southern'},
        { id: v4(), type: 'Community', site_name: 'Agricultural Dept of Stellenbosch', site_code: '', code_number: '', district:  'Winelands'},
        { id: v4(), type: 'Community', site_name: 'American Embassy', site_code: '', code_number: '', district:  'Southern'},
        { id: v4(), type: 'Community', site_name: 'Arcacia Park', site_code: '', code_number: '', district:  'Western'},
        { id: v4(), type: 'Community', site_name: 'Asanda Community', site_code: '', code_number: '', district:  'Eastern'},
        { id: v4(), type: 'Community', site_name: 'Athlone Civic Centre', site_code: '', code_number: '', district:  'Klipfontein'},
        { id: v4(), type: 'Community', site_name: 'Athlone SAPS', site_code: '', code_number: '', district:  'Klipfontein'},
        { id: v4(), type: 'Community', site_name: 'Atlantis', site_code: '', code_number: '', district:  'Winelands'},
        { id: v4(), type: 'Community', site_name: 'Atlas Company', site_code: '', code_number: '', district:  'Western'},
        { id: v4(), type: 'Community', site_name: 'Avonwood', site_code: '', code_number: '', district:  'Tygerberg'},
        { id: v4(), type: 'Community', site_name: 'Bellville Taxi Rank', site_code: '', code_number: '', district:  'Tygerberg'},
        { id: v4(), type: 'Community', site_name: 'Bishop Lavis', site_code: '', code_number: '', district:  'Tygerberg'},
        { id: v4(), type: 'Community', site_name: 'Bishop Lavis Counselling Centre', site_code: '', code_number: '', district:  'Tygerberg'},
        { id: v4(), type: 'Community', site_name: 'Bishop Lavis Shoprite', site_code: '', code_number: '', district:  'Tygerberg'},
        { id: v4(), type: 'Community', site_name: 'Blikkiesdorp', site_code: '', code_number: '', district:  'Tygerberg'},
        { id: v4(), type: 'Community', site_name: 'Blue Downs Mall', site_code: '', code_number: '', district:  'Eastern'},
        { id: v4(), type: 'Community', site_name: 'Bokmakierie/Athlone', site_code: '', code_number: '', district:  'Klipfontein'},
        { id: v4(), type: 'Community', site_name: 'Bonny Town', site_code: '', code_number: '', district:  'Southern'},
        { id: v4(), type: 'Community', site_name: 'Boys Town Cross Roads', site_code: '', code_number: '', district:  'Mitchells Plain'},
        { id: v4(), type: 'Community', site_name: 'Broadlands Park', site_code: '', code_number: '', district:  'Eastern'},
        { id: v4(), type: 'Community', site_name: 'Canal Walk', site_code: '', code_number: '', district:  'Western'},
        { id: v4(), type: 'Community', site_name: 'Cape Town Centre for the Blind (CTCB)', site_code: '', code_number: '', district:  'Western'},
        { id: v4(), type: 'Community', site_name: 'Cape Town SAPS', site_code: '', code_number: '', district:  'Cape Central'},
        { id: v4(), type: 'Community', site_name: 'Capricorn', site_code: '', code_number: '', district:  'Southern'},
        { id: v4(), type: 'Community', site_name: 'Car wash Crossroads', site_code: '', code_number: '', district:  'Mitchells Plain'},
        { id: v4(), type: 'Community', site_name: 'Casa Blanca', site_code: '', code_number: '', district:  'Mitchells Plain'},
        { id: v4(), type: 'Community', site_name: 'Civic Centre Delft', site_code: '', code_number: '', district:  'Tygerberg'},
        { id: v4(), type: 'Community', site_name: 'Claremont', site_code: '', code_number: '', district:  'Southern'},
        { id: v4(), type: 'Community', site_name: 'Claremont Station', site_code: '', code_number: '', district:  'Southern'},
        { id: v4(), type: 'Community', site_name: 'Cloetesville', site_code: '', code_number: '', district:  'Winelands'},
        { id: v4(), type: 'Community', site_name: 'Constantia SAPS', site_code: '', code_number: '', district:  'Southern'},
        { id: v4(), type: 'Community', site_name: 'Cross Roads Car Wash', site_code: '', code_number: '', district:  'Mitchells Plain'},
        { id: v4(), type: 'Community', site_name: 'Delft Community', site_code: '', code_number: '', district:  'Tygerberg'},
        { id: v4(), type: 'Community', site_name: 'Delft South', site_code: '', code_number: '', district:  'Tygerberg'},
        { id: v4(), type: 'Community', site_name: 'Delft South Library', site_code: '', code_number: '', district:  'Tygerberg'},
        { id: v4(), type: 'Community', site_name: 'Delft Taxi Rank', site_code: '', code_number: '', district:  'Tygerberg'},
        { id: v4(), type: 'Community', site_name: 'Delft Usave', site_code: '', code_number: '', district:  'Tygerberg'},
        { id: v4(), type: 'Community', site_name: 'Du Noon Shoprite', site_code: '', code_number: '', district:  'Western'},
        { id: v4(), type: 'Community', site_name: 'Eerste River Community', site_code: '', code_number: '', district:  'Eastern'},
        { id: v4(), type: 'Community', site_name: 'Eersteriver', site_code: '', code_number: '', district:  'Eastern'},
        { id: v4(), type: 'Community', site_name: 'Egoli (Ottery)', site_code: '', code_number: '', district:  'Southern'},
        { id: v4(), type: 'Community', site_name: 'Egoli (Skaapkraal)', site_code: '', code_number: '', district:  'Southern'},
        { id: v4(), type: 'Community', site_name: 'Ekuphumleni', site_code: '', code_number: '', district:  'Klipfontein'},
        { id: v4(), type: 'Community', site_name: 'Ekuphumleni/Phillip', site_code: '', code_number: '', district:  'Klipfontein'},
        { id: v4(), type: 'Community', site_name: 'Elsies River / Clarks Estate', site_code: '', code_number: '', district:  'Tygerberg'},
        { id: v4(), type: 'Community', site_name: 'Elsies River Community', site_code: '', code_number: '', district:  'Tygerberg'},
        { id: v4(), type: 'Community', site_name: 'Elsies River Owen Roads', site_code: '', code_number: '', district:  'Tygerberg'},
        { id: v4(), type: 'Community', site_name: 'Elsies Shawco/Multi-purpose Elsiesriver', site_code: '', code_number: '', district:  'Tygerberg'},
        { id: v4(), type: 'Community', site_name: 'Epping Forest', site_code: '', code_number: '', district:  'Tygerberg'},
        { id: v4(), type: 'Community', site_name: 'Erija Ville', site_code: '', code_number: '', district:  'Eastern'},
        { id: v4(), type: 'Community', site_name: 'Eureka Estate', site_code: '', code_number: '', district:  'Tygerberg'},
        { id: v4(), type: 'Community', site_name: 'Grassy Park SAPS', site_code: '', code_number: '', district:  'Southern'},
        { id: v4(), type: 'Community', site_name: 'Greenfields', site_code: '', code_number: '', district:  'Eastern'},
        { id: v4(), type: 'Community', site_name: 'Greenfields (Strand)', site_code: '', code_number: '', district:  'Eastern'},
        { id: v4(), type: 'Community', site_name: 'Gugulethu', site_code: '', code_number: '', district:  'Klipfontein'},
        { id: v4(), type: 'Community', site_name: 'Gugulethu Mall', site_code: '', code_number: '', district:  'Klipfontein'},
        { id: v4(), type: 'Community', site_name: 'Gugulethu Multi-Purpose Centre', site_code: '', code_number: '', district:  'Klipfontein'},
        { id: v4(), type: 'Community', site_name: 'Gugulethu Youth Day', site_code: '', code_number: '', district:  'Klipfontein'},
        { id: v4(), type: 'Community', site_name: 'Gustrow', site_code: '', code_number: '', district:  'Eastern'},
        { id: v4(), type: 'Community', site_name: 'Hanover Park', site_code: '', code_number: '', district:  'Klipfontein'},
        { id: v4(), type: 'Community', site_name: 'Harare Khayelitsha', site_code: '', code_number: '', district:  'Khayelitsha'},
        { id: v4(), type: 'Community', site_name: 'Hazeldene Phillipi', site_code: '', code_number: '', district:  'Mitchells Plain'},
        { id: v4(), type: 'Community', site_name: 'Heinz Food ( Wellington )', site_code: '', code_number: '', district:  'Winelands'},
        { id: v4(), type: 'Community', site_name: 'Heinz Paarl Wellington', site_code: '', code_number: '', district:  'Winelands'},
        { id: v4(), type: 'Community', site_name: 'Heinz Park', site_code: '', code_number: '', district:  'Mitchells Plain'},
        { id: v4(), type: 'Community', site_name: 'Hesketh King', site_code: '', code_number: '', district:  'Winelands'},
        { id: v4(), type: 'Community', site_name: 'Hot Favourites/Uitsig', site_code: '', code_number: '', district:  'Tygerberg'},
        { id: v4(), type: 'Community', site_name: 'Ilitha Park', site_code: '', code_number: '', district:  'Khayelitsha'},
        { id: v4(), type: 'Community', site_name: 'Imarike', site_code: '', code_number: '', district:  'Mitchells Plain'},
        { id: v4(), type: 'Community', site_name: 'Imarike Super Market', site_code: '', code_number: '', district:  'Mitchells Plain'},
        { id: v4(), type: 'Community', site_name: 'Joe Slovo', site_code: '', code_number: '', district:  'Western'},
        { id: v4(), type: 'Community', site_name: 'Kenilworth Mall', site_code: '', code_number: '', district:  'Southern'},
        { id: v4(), type: 'Community', site_name: 'Kensington Rehab', site_code: '', code_number: '', district:  'Western'},
        { id: v4(), type: 'Community', site_name: 'Khayelitsha Community', site_code: '', code_number: '', district:  'Khayelitsha'},
        { id: v4(), type: 'Community', site_name: 'Khayelitsha Grassroots', site_code: '', code_number: '', district:  'Khayelitsha'},
        { id: v4(), type: 'Community', site_name: 'Khayelitsha Mall', site_code: '', code_number: '', district:  'Khayelitsha'},
        { id: v4(), type: 'Community', site_name: 'Khayelitsha Site B', site_code: '', code_number: '', district:  'Khayelitsha'},
        { id: v4(), type: 'Community', site_name: 'Khayelitsha Site C Taxi Rank', site_code: '', code_number: '', district:  'Khayelitsha'},
        { id: v4(), type: 'Community', site_name: 'Khayelitsha Site I', site_code: '', code_number: '', district:  'Khayelitsha'},
        { id: v4(), type: 'Community', site_name: 'Khayelitsha Station', site_code: '', code_number: '', district:  'Khayelitsha'},
        { id: v4(), type: 'Community', site_name: 'Kleinvlei Community', site_code: '', code_number: '', district:  'Eastern'},
        { id: v4(), type: 'Community', site_name: 'Kraaifontein Shoprite', site_code: '', code_number: '', district:  'Northern'},
        { id: v4(), type: 'Community', site_name: 'Langa Civic', site_code: '', code_number: '', district:  'Western'},
        { id: v4(), type: 'Community', site_name: 'Langa Community', site_code: '', code_number: '', district:  'Western'},
        { id: v4(), type: 'Community', site_name: 'Langa Love Life', site_code: '', code_number: '', district:  'Western'},
        { id: v4(), type: 'Community', site_name: 'Langa Methodist Church', site_code: '', code_number: '', district:  'Western'},
        { id: v4(), type: 'Community', site_name: 'Langa Site 2', site_code: '', code_number: '', district:  'Western'},
        { id: v4(), type: 'Community', site_name: 'Langa Taxi Rank', site_code: '', code_number: '', district:  'Western'},
        { id: v4(), type: 'Community', site_name: 'Langa Terminus', site_code: '', code_number: '', district:  'Western'},
        { id: v4(), type: 'Community', site_name: 'Lentegeur Mitchells Plain', site_code: '', code_number: '', district:  'Mitchells Plain'},
        { id: v4(), type: 'Community', site_name: 'Lentergeur Station', site_code: '', code_number: '', district:  'Mitchells Plain'},
        { id: v4(), type: 'Community', site_name: 'Life Choices', site_code: '', code_number: '', district:  'Klipfontein'},
        { id: v4(), type: 'Community', site_name: 'Lookout Hill', site_code: '', code_number: '', district:  'Khayelitsha'},
        { id: v4(), type: 'Community', site_name: 'Lost City (Mitchells Plain)', site_code: '', code_number: '', district:  'Mitchells Plain'},
        { id: v4(), type: 'Community', site_name: 'Lotus River', site_code: '', code_number: '', district:  'Southern'},
        { id: v4(), type: 'Community', site_name: 'Luzuko taxi rank', site_code: '', code_number: '', district:  'Mitchells Plain'},
        { id: v4(), type: 'Community', site_name: 'Lwandle', site_code: '', code_number: '', district:  'Eastern'},
        { id: v4(), type: 'Community', site_name: 'Macassar', site_code: '', code_number: '', district:  'Eastern'},
        { id: v4(), type: 'Community', site_name: 'Macassar Community', site_code: '', code_number: '', district:  'Eastern'},
        { id: v4(), type: 'Community', site_name: 'Macassar Library', site_code: '', code_number: '', district:  'Eastern'},
        { id: v4(), type: 'Community', site_name: 'Macassar Shoprite', site_code: '', code_number: '', district:  'Eastern'},
        { id: v4(), type: 'Community', site_name: 'Maitland Station', site_code: '', code_number: '', district:  'Western'},
        { id: v4(), type: 'Community', site_name: 'Malawi Camp', site_code: '', code_number: '', district:  'Tygerberg'},
        { id: v4(), type: 'Community', site_name: 'Malibu', site_code: '', code_number: '', district:  'Eastern'},
        { id: v4(), type: 'Community', site_name: 'Manenberg (Zone 1)', site_code: '', code_number: '', district:  'Klipfontein'},
        { id: v4(), type: 'Community', site_name: 'Manenberg (Zone 4)', site_code: '', code_number: '', district:  'Klipfontein'},
        { id: v4(), type: 'Community', site_name: 'Manenberg Community', site_code: '', code_number: '', district:  'Klipfontein'},
        { id: v4(), type: 'Community', site_name: 'Manenberg Peoples Centre', site_code: '', code_number: '', district:  'Klipfontein'},
        { id: v4(), type: 'Community', site_name: 'Maphindi Community', site_code: '', code_number: '', district:  'Klipfontein'},
        { id: v4(), type: 'Community', site_name: 'Marcus Garvey Phillipi', site_code: '', code_number: '', district:  'Mitchells Plain'},
        { id: v4(), type: 'Community', site_name: 'Masiphumelele', site_code: '', code_number: '', district:  'Southern'},
        { id: v4(), type: 'Community', site_name: 'Matie Town', site_code: '', code_number: '', district:  'Winelands'},
        { id: v4(), type: 'Community', site_name: 'Maynard Mall', site_code: '', code_number: '', district:  'Southern'},
        { id: v4(), type: 'Community', site_name: 'Melton Rose', site_code: '', code_number: '', district:  'Eastern'},
        { id: v4(), type: 'Community', site_name: 'Melton Rose Station', site_code: '', code_number: '', district:  'Eastern'},
        { id: v4(), type: 'Community', site_name: 'Mfuleni', site_code: '', code_number: '', district:  'Eastern'},
        { id: v4(), type: 'Community', site_name: 'Mfuleni SAPS', site_code: '', code_number: '', district:  'Eastern'},
        { id: v4(), type: 'Community', site_name: 'Military Heights', site_code: '', code_number: '', district:  'Southern'},
        { id: v4(), type: 'Community', site_name: 'Mitchells Plain Eastridge', site_code: '', code_number: '', district:  'Mitchells Plain'},
        { id: v4(), type: 'Community', site_name: 'Mitchells Plain Rocklands', site_code: '', code_number: '', district:  'Mitchells Plain'},
        { id: v4(), type: 'Community', site_name: 'Mitchells Plain Town Centre', site_code: '', code_number: '', district:  'Mitchells Plain'},
        { id: v4(), type: 'Community', site_name: 'Monwabisi Park', site_code: '', code_number: '', district:  'Khayelitsha'},
        { id: v4(), type: 'Community', site_name: 'Morkels Cottages', site_code: '', code_number: '', district:  'Tygerberg'},
        { id: v4(), type: 'Community', site_name: 'N2 Gate Way Delft', site_code: '', code_number: '', district:  'Tygerberg'},
        { id: v4(), type: 'Community', site_name: 'New Cross Road', site_code: '', code_number: '', district:  'Mitchells Plain'},
        { id: v4(), type: 'Community', site_name: 'New Woodlands', site_code: '', code_number: '', district:  'Mitchells Plain'},
        { id: v4(), type: 'Community', site_name: 'Nyanga 1', site_code: '', code_number: '', district:  'Klipfontein'},
        { id: v4(), type: 'Community', site_name: 'Nyanga Junction', site_code: '', code_number: '', district:  'Klipfontein'},
        { id: v4(), type: 'Community', site_name: 'Nyanga Taxi Rank/Terminus', site_code: '', code_number: '', district:  'Klipfontein'},
        { id: v4(), type: 'Community', site_name: 'Nyanga/Cross Roads', site_code: '', code_number: '', district:  'Klipfontein'},
        { id: v4(), type: 'Community', site_name: 'Old Cross Roads', site_code: '', code_number: '', district:  'Mitchells Plain'},
        { id: v4(), type: 'Community', site_name: 'Ottery Hyper', site_code: '', code_number: '', district:  'Southern'},
        { id: v4(), type: 'Community', site_name: 'Overcome Heights', site_code: '', code_number: '', district:  'Southern'},
        { id: v4(), type: 'Community', site_name: 'Owen Road', site_code: '', code_number: '', district:  'Tygerberg'},
        { id: v4(), type: 'Community', site_name: 'Paarl Mall', site_code: '', code_number: '', district:  'Winelands'},
        { id: v4(), type: 'Community', site_name: 'Parow Centre', site_code: '', code_number: '', district:  'Tygerberg'},
        { id: v4(), type: 'Community', site_name: 'Philippi 2', site_code: '', code_number: '', district:  'Mitchells Plain'},
        { id: v4(), type: 'Community', site_name: 'Philippi Car Wash', site_code: '', code_number: '', district:  'Mitchells Plain'},
        { id: v4(), type: 'Community', site_name: 'Philippi Community', site_code: '', code_number: '', district:  'Mitchells Plain'},
        { id: v4(), type: 'Community', site_name: 'Philippi East', site_code: '', code_number: '', district:  'Mitchells Plain'},
        { id: v4(), type: 'Community', site_name: 'Philippi Food Bank', site_code: '', code_number: '', district:  'Mitchells Plain'},
        { id: v4(), type: 'Community', site_name: 'Philippi Library', site_code: '', code_number: '', district:  'Mitchells Plain'},
        { id: v4(), type: 'Community', site_name: 'Philippi Plaza', site_code: '', code_number: '', district:  'Mitchells Plain'},
        { id: v4(), type: 'Community', site_name: 'Philippi Shoprite', site_code: '', code_number: '', district:  'Mitchells Plain'},
        { id: v4(), type: 'Community', site_name: 'Philippi Small Business', site_code: '', code_number: '', district:  'Mitchells Plain'},
        { id: v4(), type: 'Community', site_name: 'Philippi Station', site_code: '', code_number: '', district:  'Mitchells Plain'},
        { id: v4(), type: 'Community', site_name: 'Philippi Stock Road', site_code: '', code_number: '', district:  'Mitchells Plain'},
        { id: v4(), type: 'Community', site_name: 'Phumlani', site_code: '', code_number: '', district:  'Southern'},
        { id: v4(), type: 'Community', site_name: 'Pick n Pay-Ottery', site_code: '', code_number: '', district:  'Southern'},
        { id: v4(), type: 'Community', site_name: 'Polyoak', site_code: '', code_number: '', district:  'Southern'},
        { id: v4(), type: 'Community', site_name: 'Pooke se bos', site_code: '', code_number: '', district:  'Klipfontein'},
        { id: v4(), type: 'Community', site_name: 'Portlands(Mitchells Plain)', site_code: '', code_number: '', district:  'Mitchells Plain'},
        { id: v4(), type: 'Community', site_name: 'Retreat Station', site_code: '', code_number: '', district:  'Southern'},
        { id: v4(), type: 'Community', site_name: 'Rocklands', site_code: '', code_number: '', district:  'Mitchells Plain'},
        { id: v4(), type: 'Community', site_name: 'Rocklands Library', site_code: '', code_number: '', district:  'Mitchells Plain'},
        { id: v4(), type: 'Community', site_name: 'Rocklands(Shoprite)', site_code: '', code_number: '', district:  'Mitchells Plain'},
        { id: v4(), type: 'Community', site_name: 'Rondomskrik', site_code: '', code_number: '', district:  'Westcoast'},
        { id: v4(), type: 'Community', site_name: 'Salesians Institute', site_code: '', code_number: '', district:  'Western'},
        { id: v4(), type: 'Community', site_name: 'Salvation Army', site_code: '', code_number: '', district:  'Winelands'},
        { id: v4(), type: 'Community', site_name: 'Samora Machel', site_code: '', code_number: '', district:  'Mitchells Plain'},
        { id: v4(), type: 'Community', site_name: 'Samora Machel Creche', site_code: '', code_number: '', district:  'Mitchells Plain'},
        { id: v4(), type: 'Community', site_name: 'Samora Machel SAPS', site_code: '', code_number: '', district:  'Mitchells Plain'},
        { id: v4(), type: 'Community', site_name: 'Samora Spar', site_code: '', code_number: '', district:  'Mitchells Plain'},
        { id: v4(), type: 'Community', site_name: 'SAPS Finger Prict Mitchells Plain', site_code: '', code_number: '', district:  'Mitchells Plain'},
        { id: v4(), type: 'Community', site_name: 'SAPS Kensington', site_code: '', code_number: '', district:  'Western'},
        { id: v4(), type: 'Community', site_name: 'Saverite New CrossRoad', site_code: '', code_number: '', district:  'Mitchells Plain'},
        { id: v4(), type: 'Community', site_name: 'Selecta', site_code: '', code_number: '', district:  'Mitchells Plain'},
        { id: v4(), type: 'Community', site_name: 'Selecta Sea', site_code: '', code_number: '', district:  'Mitchells Plain'},
        { id: v4(), type: 'Community', site_name: 'Self Help Manenberg', site_code: '', code_number: '', district:  'Klipfontein'},
        { id: v4(), type: 'Community', site_name: 'Shoprite Charlesville', site_code: '', code_number: '', district:  'Tygerberg'},
        { id: v4(), type: 'Community', site_name: 'Shoprite Cravenby', site_code: '', code_number: '', district:  'Tygerberg'},
        { id: v4(), type: 'Community', site_name: 'Shoprite Park Parow', site_code: '', code_number: '', district:  'Tygerberg'},
        { id: v4(), type: 'Community', site_name: 'Silvertree - Manenberg', site_code: '', code_number: '', district:  'Klipfontein'},
        { id: v4(), type: 'Community', site_name: 'Simons Town SAPS', site_code: '', code_number: '', district:  'Southern'},
        { id: v4(), type: 'Community', site_name: 'Sir Lowry Pass', site_code: '', code_number: '', district:  'Eastern'},
        { id: v4(), type: 'Community', site_name: 'Sir Lowry Pass/Nomzamo', site_code: '', code_number: '', district:  'Eastern'},
        { id: v4(), type: 'Community', site_name: 'Siyahlala (Phillipi)', site_code: '', code_number: '', district:  'Mitchells Plain'},
        { id: v4(), type: 'Community', site_name: 'Somerset Mall', site_code: '', code_number: '', district:  'Eastern'},
        { id: v4(), type: 'Community', site_name: 'Spes Bona Hostel', site_code: '', code_number: '', district:  'Klipfontein'},
        { id: v4(), type: 'Community', site_name: 'St Aidans', site_code: '', code_number: '', district:  'Southern'},
        { id: v4(), type: 'Community', site_name: 'St Faith Church (Plumstead)', site_code: '', code_number: '', district:  'Southern'},
        { id: v4(), type: 'Community', site_name: 'St Marks', site_code: '', code_number: '', district:  'Western'},
        { id: v4(), type: 'Community', site_name: 'St Marys Church', site_code: '', code_number: '', district:  'Western'},
        { id: v4(), type: 'Community', site_name: 'St Pauls Church', site_code: '', code_number: '', district:  'Southern'},
        { id: v4(), type: 'Community', site_name: 'St Phillips', site_code: '', code_number: '', district:  'Southern'},
        { id: v4(), type: 'Community', site_name: 'ST. James Anglican Church', site_code: '', code_number: '', district:  'Western'},
        { id: v4(), type: 'Community', site_name: 'ST. Mary Woodstock', site_code: '', code_number: '', district:  'Western'},
        { id: v4(), type: 'Community', site_name: 'Steenberg', site_code: '', code_number: '', district:  'Southern'},
        { id: v4(), type: 'Community', site_name: 'Steenberg Shoprite', site_code: '', code_number: '', district:  'Southern'},
        { id: v4(), type: 'Community', site_name: 'Steenberg Station', site_code: '', code_number: '', district:  'Southern'},
        { id: v4(), type: 'Community', site_name: 'Stellenbosch Station', site_code: '', code_number: '', district:  'Winelands'},
        { id: v4(), type: 'Community', site_name: 'Stock Road', site_code: '', code_number: '', district:  'Mitchells Plain'},
        { id: v4(), type: 'Community', site_name: 'Strand', site_code: '', code_number: '', district:  'Eastern'},
        { id: v4(), type: 'Community', site_name: 'Strand - Shoprite', site_code: '', code_number: '', district:  'Eastern'},
        { id: v4(), type: 'Community', site_name: 'Tafelsig Mitchells Plain', site_code: '', code_number: '', district:  'Mitchells Plain'},
        { id: v4(), type: 'Community', site_name: 'Tambo Village', site_code: '', code_number: '', district:  'Klipfontein'},
        { id: v4(), type: 'Community', site_name: 'The Range', site_code: '', code_number: '', district:  'Tygerberg'},
        { id: v4(), type: 'Community', site_name: 'Tygervalley', site_code: '', code_number: '', district:  'Tygerberg'},
        { id: v4(), type: 'Community', site_name: 'Uluntu Centre', site_code: '', code_number: '', district:  'Tygerberg'},
        { id: v4(), type: 'Community', site_name: 'Uitsig Community', site_code: '', code_number: '', district:  'Klipfontein'},
        { id: v4(), type: 'Community', site_name: 'Voorbrug Community', site_code: '', code_number: '', district:  'Tygerberg'},
        { id: v4(), type: 'Community', site_name: 'Viking Fishing', site_code: '', code_number: '', district:  'Central'},
        { id: v4(), type: 'Community', site_name: 'Vygieskraal', site_code: '', code_number: '', district:  'Klipfontein'},
        { id: v4(), type: 'Community', site_name: 'Wallacedene Taxi Rank', site_code: '', code_number: '', district:  'Northern'},
        { id: v4(), type: 'Community', site_name: 'Wellington', site_code: '', code_number: '', district:  'Winelands'},
        { id: v4(), type: 'Community', site_name: 'Wesbank', site_code: '', code_number: '', district:  'Eastern'},
        { id: v4(), type: 'Community', site_name: 'Wesbank Spar', site_code: '', code_number: '', district:  'Eastern'},
        { id: v4(), type: 'Community', site_name: 'Westlake Community', site_code: '', code_number: '', district:  'Southern'},
        { id: v4(), type: 'Community', site_name: 'Westridge Civic Centre', site_code: '', code_number: '', district:  'Mitchells Plain'},
        { id: v4(), type: 'Community', site_name: 'Winners', site_code: '', code_number: '', district:  'Mitchells Plain'},
        { id: v4(), type: 'Community', site_name: 'Zola Strand', site_code: '', code_number: '', district:  'Eastern'},
      ]);
    });
};
