const { v4 } = require("uuid");

exports.seed = function(knex) {
  // Deletes ALL existing entries
  return knex('areas').del()
    .then(function () {
      // Inserts seed entries
      return knex('areas').insert([
        {id: v4(), area: 'Acacia Park'},
        {id: v4(), area: 'Athlone'},
        {id: v4(), area: 'Atlantis'},
        {id: v4(), area: 'Belgravia'},
        {id: v4(), area: 'Blue Downs'},
        {id: v4(), area: 'Bonteheuwel'},
        {id: v4(), area: 'Bishop Lavis'},
        {id: v4(), area: 'Cape Town CBD'},
        {id: v4(), area: 'Capricon Park'},
        {id: v4(), area: 'Century City'},
        {id: v4(), area: 'Charlesville'},
        {id: v4(), area: 'Claremont'},
        {id: v4(), area: 'COCT Crawford'},
        {id: v4(), area: 'COCT Gugulethu'},
        {id: v4(), area: 'COCT Pinelands'},
        {id: v4(), area: 'COCT Athlone'},
        {id: v4(), area: 'COCT Thornton'},
        {id: v4(), area: 'COCT Wynberg'},
        {id: v4(), area: 'Constantia'},
        {id: v4(), area: 'Crossroads'},
        {id: v4(), area: 'De Waterkant'},
        {id: v4(), area: 'Delft'},
        {id: v4(), area: 'Diep River'},
        {id: v4(), area: 'Du Noon'},
        {id: v4(), area: 'Eastridge'},
        {id: v4(), area: 'Eeerste Rivier'},
        {id: v4(), area: 'Elsies River'},
        {id: v4(), area: 'Epping'},
        {id: v4(), area: 'Goodwood'},
        {id: v4(), area: 'Grassy Park'},
        {id: v4(), area: 'Green Point'},
        {id: v4(), area: 'Hanover Park'},
        {id: v4(), area: 'Heinz Park'},
        {id: v4(), area: 'Joe Slovo'},
        {id: v4(), area: 'Kenilworth'},
        {id: v4(), area: 'Kensington'},
        {id: v4(), area: 'Khayelitsha'},
        {id: v4(), area: 'Kraaifontein'},
        {id: v4(), area: 'Lansdowne'},
        {id: v4(), area: 'Langa'},
        {id: v4(), area: 'Lentegeur'},
        {id: v4(), area: 'Lotus River'},
        {id: v4(), area: 'Macassar'},
        {id: v4(), area: 'Maitland'},
        {id: v4(), area: 'Malawi Camp'},
        {id: v4(), area: 'Malmesbury'},
        {id: v4(), area: 'Manenberg'},
        {id: v4(), area: 'Masiphumelele'},
        {id: v4(), area: 'Mfuleni'},
        {id: v4(), area: 'MItchells Plain Town Center'},
        {id: v4(), area: 'Mowbray'},
        {id: v4(), area: 'New Woodlands'},
        {id: v4(), area: 'Nyanga'},
        {id: v4(), area: 'Ottery'},
        {id: v4(), area: 'Overcome'},
        {id: v4(), area: 'Paarl'},
        {id: v4(), area: 'Parow'},
        {id: v4(), area: 'Philippi'},
        {id: v4(), area: 'Pinelands'},
        {id: v4(), area: 'Plumstead'},
        {id: v4(), area: 'Portlands'},
        {id: v4(), area: 'Retreat'},
        {id: v4(), area: 'Rocklands'},
        {id: v4(), area: 'Rondebosch'},
        {id: v4(), area: 'Rylands'},
        {id: v4(), area: 'Salt River'},
        {id: v4(), area: 'Samora Machel'},
        {id: v4(), area: 'Simons Town'},
        {id: v4(), area: 'Sir Lowrys Pass'},
        {id: v4(), area: 'Somerset West'},
        {id: v4(), area: 'Steenberg'},
        {id: v4(), area: 'Stellenbosch'},
        {id: v4(), area: 'Tafelsig'},
        {id: v4(), area: 'Thornton'},
        {id: v4(), area: 'Wellington'},
        {id: v4(), area: 'Wesbank'},
        {id: v4(), area: 'Westlake'},
        {id: v4(), area: 'Westridge'},
        {id: v4(), area: 'Wetton'},
        {id: v4(), area: 'Woodstock'},
        {id: v4(), area: 'Wynberg'},
        {id: v4(), area: 'Zonnebloem'},
      ]);
    });
};
